language: haskell
notifications:
  email: false

repo_token: XXfgpYZr0ll7yTzRkib55x5OtdBqxB6dA

before_install:
  - cabal install hpc-coveralls
script:
  - cabal configure --enable-tests --enable-library-coverage && cabal build
  - run-cabal-test --show-details=always
after_script:
  - hpc-coveralls calc